### PR TITLE
Updated Blizzard and Steam CDN URLs that were breaking the updaters

### PR DESCRIPTION
**Pull request by TheGrandPackard**
Thanks for the project you put together. It's been hugely helpful. Here is what I needed to change recently to get it working again. My changes Includes more domains than #29 and #27. I found my updated domains from https://github.com/uklans/cache-domains

### CODE REVIEW

**Comment by JasonRivers** [comment]
Thanks! I'll Merge this in, However this will soon change, we're working at generating our domain list from a better maintained list, which also means we only have a single location to update domains, this image will then have auto-generated DNS from the list.

So going forwards Once this work is done, check here for domain updates: https://github.com/uklans/cache-domains

**Comment by TheGrandPackard** [comment]
Awesome, thanks @JasonRivers ! I look forward to an auto-generating method - keep up the great work!

**Comment by TheGrandPackard** [comment]
Hi @sta3b! I don't see it on the maintained list at https://github.com/uklans/cache-domains. I will be setting up another caching server for a LAN party on the 25th of this month, so I'll see then if it's required or not. If you can confirm that it's a CDN domain for steam before then, I'd recommend opening an issue or pull request at https://github.com/uklans/cache-domains

**Comment by sta3b** [comment]
@TheGrandPackard alright awesome, and may i have ur email please ? got a couple of questions regarding the steamcache. Thank you!

**Comment by TheGrandPackard** [comment]
Sure, I have a gmail address with the same username as my github profile.

**Comment by JasonRivers** [comment]
The DNS container has now been updated to get it's list from uklans/cache-domains, it will do this at startup. 

The only thing to note here is that if you are using ```USE_GENERIC_CACHE```, then you might want to either disable some services (using ```DISABLE_${SERVICE}=true``` ) or fire up generic containers for those services.

**Comment by TheGrandPackard** [comment]
@JasonRivers Fantastic work! I look forward to testing this out next weekend for caching blizzard/steam games again. Thanks for the updates!

**Pull request merged**
